"""
Publication-quality figure: figure_confusion_matrix.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# =========================
# Config
# =========================

OUTPUT_DIR = Path("docs/figures")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_confusion_matrix"
SAVE_FORMATS = ["png"]
DPI = 150


# =========================
# Style
# =========================

PAPER_PALETTE = {

    "blue_main": "#5B8DB8",

    "blue_dark": "#3E6F95",

    "blue_light": "#BFD8EA",

    "teal_main": "#6FA8A6",

    "teal_dark": "#4D8583",

    "green_light": "#CFE8D5",

    "green_main": "#9CCB9E",

    "yellow_light": "#F3E6B3",

    "orange_light": "#E8B77D",

    "orange_main": "#D99A5E",

    "purple_light": "#C9BEDF",

    "pink_light": "#E7C1C0",

    "gray_light": "#E8ECEF",

    "gray": "#BFC7CD",

    "gray_dark": "#66727C",

    "positive": "#6FA8A6",

    "negative": "#D99A5E",

    "neutral": "#BFC7CD",

    "highlight": "#F3C567",

}


def apply_paper_style(font_size=12, linewidth=1.2):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": linewidth,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "svg.fonttype": "none",
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })


# =========================
# Data
# =========================

def load_data():

        # TODO: Replace this example data with your real data.
        class_names = ["N1", "N2", "N3", "REM", "Awake"]
        matrix = np.array([
            [0.72, 0.12, 0.08, 0.05, 0.03],
            [0.10, 0.68, 0.14, 0.06, 0.02],
            [0.06, 0.12, 0.74, 0.05, 0.03],
            [0.04, 0.06, 0.06, 0.80, 0.04],
            [0.02, 0.02, 0.02, 0.04, 0.90],
        ])
        return class_names, matrix


def validate_data(data):

        class_names, matrix = data
        if matrix.shape[0] != matrix.shape[1]:
            raise ValueError(f"Confusion matrix must be square, got {matrix.shape}")
        if len(class_names) != matrix.shape[0]:
            raise ValueError(f"Class names ({len(class_names)}) != matrix size ({matrix.shape[0]})")
        for i, row in enumerate(matrix):
            row_sum = row.sum()
            if not (0.95 <= row_sum <= 1.05):
                print(f"Warning: Row {i} ({class_names[i]}) sums to {row_sum:.3f}, expected ~1.0")


# =========================
# Plot
# =========================

def plot_figure(data):

        apply_paper_style()
        class_names, matrix = data

        fig, ax = plt.subplots(figsize=(6, 5.5))

        im = ax.imshow(matrix, cmap="Blues", aspect="auto", vmin=0, vmax=1)

        ax.set_xticks(np.arange(len(class_names)))
        ax.set_yticks(np.arange(len(class_names)))
        ax.set_xticklabels(class_names)
        ax.set_yticklabels(class_names)

        for i in range(len(class_names)):
            for j in range(len(class_names)):
                value = matrix[i, j]
                text_color = "white" if value < 0.6 else "black"
                if i == j:
                    font_weight = "bold"
                else:
                    font_weight = "normal"
                ax.annotate(f"{value:.0%}",
                           xy=(j, i), ha="center", va="center",
                           color=text_color, fontsize=10, fontweight=font_weight)

        ax.set_xlabel("Predicted Label")
        ax.set_ylabel("True Label")
        ax.set_title("Confusion Matrix (Normalized per True Class)")

        fig.tight_layout(pad=1.2)
        return fig


# =========================
# Export
# =========================

def save_figure(fig, name=FIG_NAME):
    saved_paths = []
    for fmt in SAVE_FORMATS:
        path = OUTPUT_DIR / f"{name}.{fmt}"
        fig.savefig(path, dpi=DPI, bbox_inches="tight")
        saved_paths.append(path)
    return saved_paths


def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    saved_paths = save_figure(fig)
    print("Saved files:")
    for path in saved_paths:
        print(f"  - {path}")


if __name__ == "__main__":
    main()
