"""
Publication-quality figure: figure_eeg_topomap.

Generated by paper-figure-codegen.
Requires: mne (optional, skips gracefully if not installed)
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

OUTPUT_DIR = Path("docs/figures")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_eeg_topomap"
DPI = 150

def main():
    try:
        import mne
    except ImportError:
        print("Skipping eeg_topomap: mne not installed.")
        print("Install with: pip install mne")
        # Generate a simple placeholder image
        fig, ax = plt.subplots(figsize=(5, 5))
        ax.text(0.5, 0.5, "EEG Topomap\n(requires mne)",
                ha="center", va="center", fontsize=14,
                transform=ax.transAxes)
        ax.set_xlim(-1.2, 1.2)
        ax.set_ylim(-1.2, 1.2)
        circle = plt.Circle((0, 0), 1.0, fill=False, edgecolor="#5B8DB8", linewidth=2)
        ax.add_patch(circle)
        ax.axis("off")

        np.random.seed(42)
        n_channels = 10
        angles = np.linspace(0, 2 * np.pi, n_channels, endpoint=False)
        ch_x = 0.8 * np.cos(angles)
        ch_y = 0.8 * np.sin(angles)
        ch_x = np.append(ch_x, 0.0)
        ch_y = np.append(ch_y, 0.0)
        values = np.random.uniform(0.3, 0.9, n_channels + 1)

        for cx, cy, v in zip(ch_x, ch_y, values):
            color = plt.cm.YlGnBu(v)
            ax.plot(cx, cy, "o", color=color, markersize=14, markeredgecolor="white", markeredgewidth=1)
            ax.annotate(f"{v:.2f}", (cx, cy), ha="center", va="center", fontsize=7, fontweight="bold")

        ch_names = [f"Ch{i}" for i in range(n_channels)] + ["Cz"]
        for cx, cy, name in zip(ch_x, ch_y, ch_names):
            ax.annotate(name, (cx, cy + 0.12), ha="center", fontsize=7)

        fig.tight_layout()
        path = OUTPUT_DIR / f"{FIG_NAME}.png"
        fig.savefig(path, dpi=DPI, bbox_inches="tight")
        print(f"Saved (placeholder): {path}")
        return

    # Full mne-based topomap
    from mne.viz import plot_topomap

    ch_names = [
        "Fp1", "Fp2", "F3", "F4", "C3", "C4", "P3", "P4", "O1", "O2", "Cz",
    ]
    info = mne.create_info(ch_names, sfreq=256, ch_types="eeg")
    info.set_montage("standard_1020")

    np.random.seed(42)
    values = np.random.uniform(0.3, 0.9, len(ch_names))

    fig, ax = plt.subplots(figsize=(5, 5))
    plot_topomap(values, info, axes=ax, show=False, cmap="YlGnBu", sphere=(0, 0, 0, 1))
    ax.set_title("EEG Channel Importance")

    fig.tight_layout()
    path = OUTPUT_DIR / f"{FIG_NAME}.png"
    fig.savefig(path, dpi=DPI, bbox_inches="tight")
    print(f"Saved: {path}")

if __name__ == "__main__":
    main()