"""
Publication-quality figure: figure_flowchart_composite.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

OUTPUT_DIR = Path("docs/figures")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_flowchart_composite"
DPI = 150

def apply_paper_style(font_size=12):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": 1.2,
        "pdf.fonttype": 42,
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })

def plot_figure():
    apply_paper_style()

    fig = plt.figure(figsize=(10, 6))

    # Left half: flowchart
    ax_flow = fig.add_axes([0.02, 0.05, 0.45, 0.88])
    ax_flow.set_xlim(0, 10)
    ax_flow.set_ylim(0, 10)
    ax_flow.axis("off")

    steps = [
        ("Raw Data", 5, 9, "#BFD8EA"),
        ("Preprocessing", 5, 7, "#CFE8D5"),
        ("Feature\nExtraction", 5, 5, "#F3E6B3"),
        ("Model\nTraining", 5, 3, "#E8B77D"),
        ("Evaluation", 5, 1, "#9CCB9E"),
    ]

    for label, x, y, color in steps:
        box = mpatches.FancyBboxPatch(
            (x - 1.5, y - 0.6), 3, 1.2,
            boxstyle="round,pad=0.15", facecolor=color, edgecolor="#66727C", linewidth=1.2,
        )
        ax_flow.add_patch(box)
        ax_flow.text(x, y, label, ha="center", va="center", fontsize=9, fontweight="bold")

    for i in range(len(steps) - 1):
        _, _, y1, _ = steps[i]
        _, _, y2, _ = steps[i + 1]
        ax_flow.annotate("", xy=(5, y2 + 0.65), xytext=(5, y1 - 0.65),
                        arrowprops=dict(arrowstyle="->", color="#66727C", lw=1.5))

    ax_flow.text(5, 10, "Pipeline Overview", ha="center", fontsize=12, fontweight="bold")

    # Right half: results bar chart
    ax_bar = fig.add_axes([0.55, 0.12, 0.42, 0.75])

    methods = ["Baseline", "CNN", "LSTM", "Ours"]
    scores = [0.78, 0.84, 0.86, 0.93]
    colors = ["#5B8DB8", "#6FA8A6", "#9CCB9E", "#D99A5E"]

    bars = ax_bar.barh(methods, scores, color=colors, edgecolor="white", linewidth=0.5)
    for bar in bars:
        width = bar.get_width()
        ax_bar.annotate(f"{width:.2f}", xy=(width + 0.01, bar.get_y() + bar.get_height() / 2),
                       va="center", fontsize=9)

    ax_bar.set_xlim(0, 1.05)
    ax_bar.set_xlabel("Accuracy")
    ax_bar.set_title("Results", fontsize=12, fontweight="bold")
    ax_bar.grid(axis="x", linestyle="--", linewidth=0.6, alpha=0.35)

    return fig

def save_figure(fig):
    path = OUTPUT_DIR / f"{FIG_NAME}.png"
    fig.savefig(path, dpi=DPI, bbox_inches="tight")
    print(f"Saved: {path}")

def main():
    fig = plot_figure()
    save_figure(fig)

if __name__ == "__main__":
    main()