"""
Publication-quality figure: figure_grouped_bar.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# =========================
# Config
# =========================

OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_grouped_bar"
SAVE_FORMATS = ["png", "pdf", "svg"]
DPI = 300


# =========================
# Style
# =========================

PAPER_PALETTE = {

    "blue_main": "#5B8DB8",

    "blue_dark": "#3E6F95",

    "blue_light": "#BFD8EA",

    "teal_main": "#6FA8A6",

    "teal_dark": "#4D8583",

    "green_light": "#CFE8D5",

    "green_main": "#9CCB9E",

    "yellow_light": "#F3E6B3",

    "orange_light": "#E8B77D",

    "orange_main": "#D99A5E",

    "purple_light": "#C9BEDF",

    "pink_light": "#E7C1C0",

    "gray_light": "#E8ECEF",

    "gray": "#BFC7CD",

    "gray_dark": "#66727C",

    "positive": "#6FA8A6",

    "negative": "#D99A5E",

    "neutral": "#BFC7CD",

    "highlight": "#F3C567",

}


def apply_paper_style(font_size=12, linewidth=1.2):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": linewidth,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "svg.fonttype": "none",
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })


# =========================
# Data
# =========================

def load_data():

        # TODO: Replace this example data with your real data.
        methods = ["Baseline", "CNN", "Transformer", "Ours"]
        metrics = ["Accuracy", "F1", "AUC"]
        data = {
            "Baseline": [0.8100, 0.7900, 0.8500],
            "CNN": [0.8500, 0.8300, 0.8800],
            "Transformer": [0.8700, 0.8500, 0.9000],
            "Ours": [0.9100, 0.8900, 0.9400],
        }
        return methods, metrics, data


def validate_data(data):

        methods, metrics, data = data
        if len(data) != len(methods):
            raise ValueError(f"Expected {len(methods)} methods, got {len(data)}")
        for name, vals in data.items():
            if len(vals) != len(metrics):
                raise ValueError(f"Method {name}: expected {len(metrics)} values, got {len(vals)}")


# =========================
# Plot
# =========================

def plot_figure(data):

        apply_paper_style()
        methods, metrics, data = data

        n_methods = len(methods)
        n_metrics = len(metrics)
        x = np.arange(n_metrics)
        width = 0.8 / n_methods

        fig, ax = plt.subplots(figsize=(6, 4.5))

        colors = [
            "#5B8DB8",
            "#6FA8A6",
            "#9CCB9E",
            "#F3E6B3",
        ]

        for i, method in enumerate(methods):
            offset = (i - n_methods / 2 + 0.5) * width
            bars = ax.bar(x + offset, data[method], width, label=method, color=colors[i % len(colors)])
            for bar in bars:
                height = bar.get_height()
                ax.annotate(f"{height:.2f}",
                            xy=(bar.get_x() + bar.get_width() / 2, height),
                            xytext=(0, 3), textcoords="offset points",
                            ha="center", va="bottom", fontsize=8)

        ax.set_xticks(x)
        ax.set_xticklabels(metrics)
        ax.set_ylabel("Score")
        ax.set_title("Method Comparison")
        ax.legend(loc="upper right")
        ax.grid(axis="y", linestyle="--", linewidth=0.6, alpha=0.35)

        y_min = min(min(v) for v in data.values())
        ax.set_ylim(max(0, y_min - 0.05), 1.0)

        fig.tight_layout(pad=1.2)
        return fig


# =========================
# Export
# =========================

def save_figure(fig, name=FIG_NAME):
    saved_paths = []
    for fmt in SAVE_FORMATS:
        path = OUTPUT_DIR / f"{name}.{fmt}"
        fig.savefig(path, dpi=DPI, bbox_inches="tight")
        saved_paths.append(path)
    return saved_paths


def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    saved_paths = save_figure(fig)
    print("Saved files:")
    for path in saved_paths:
        print(f"  - {path}")


if __name__ == "__main__":
    main()
