"""
Publication-quality figure: figure_heatmap.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

OUTPUT_DIR = Path("docs/figures")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_heatmap"
DPI = 150

def apply_paper_style(font_size=12):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": 1.2,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })

def load_data():
    features = ["Alpha", "Beta", "Gamma", "Theta", "Delta"]
    regions = ["Frontal", "Temporal", "Parietal", "Occipital"]
    np.random.seed(42)
    matrix = np.array([
        [0.82, 0.45, 0.67, 0.23, 0.12],
        [0.34, 0.78, 0.56, 0.41, 0.29],
        [0.56, 0.62, 0.91, 0.38, 0.15],
        [0.21, 0.33, 0.42, 0.85, 0.68],
    ])
    return features, regions, matrix

def validate_data(data):
    features, regions, matrix = data
    assert matrix.shape == (len(regions), len(features))

def plot_figure(data):
    apply_paper_style()
    features, regions, matrix = data

    fig, ax = plt.subplots(figsize=(6, 5))

    im = ax.imshow(matrix, cmap="YlGnBu", aspect="auto")

    ax.set_xticks(np.arange(len(features)))
    ax.set_yticks(np.arange(len(regions)))
    ax.set_xticklabels(features)
    ax.set_yticklabels(regions)

    for i in range(len(regions)):
        for j in range(len(features)):
            val = matrix[i, j]
            text_color = "white" if val > 0.65 else "black"
            ax.annotate(f"{val:.2f}", xy=(j, i), ha="center", va="center",
                       color=text_color, fontsize=9)

    fig.colorbar(im, ax=ax, label="Importance", shrink=0.8)
    ax.set_title("Feature Importance by Brain Region")

    fig.tight_layout(pad=1.2)
    return fig

def save_figure(fig):
    path = OUTPUT_DIR / f"{FIG_NAME}.png"
    fig.savefig(path, dpi=DPI, bbox_inches="tight")
    print(f"Saved: {path}")

def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    save_figure(fig)

if __name__ == "__main__":
    main()