"""
Publication-quality figure: figure_histogram_kde.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

OUTPUT_DIR = Path("docs/figures")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_histogram_kde"
DPI = 150

def apply_paper_style(font_size=12):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": 1.2,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })

def load_data():
    np.random.seed(42)
    values = np.concatenate([
        np.random.normal(0.6, 0.12, 150),
        np.random.normal(0.85, 0.08, 100),
    ])
    return values

def validate_data(data):
    assert len(data) > 0

def plot_figure(data):
    apply_paper_style()

    fig, ax = plt.subplots(figsize=(7, 4.5))

    ax.hist(data, bins=30, density=True, color="#5B8DB8", alpha=0.6,
            edgecolor="white", linewidth=0.5, label="Histogram")

    try:
        from scipy.stats import gaussian_kde
        kde = gaussian_kde(data)
        x_grid = np.linspace(data.min() - 0.1, data.max() + 0.1, 300)
        ax.plot(x_grid, kde(x_grid), color="#D99A5E", linewidth=2.0, label="KDE")
    except ImportError:
        bins_edges = np.histogram_bin_edges(data, bins=30)
        counts, _ = np.histogram(data, bins=bins_edges, density=True)
        centers = 0.5 * (bins_edges[:-1] + bins_edges[1:])
        from numpy import convolve
        kernel = np.exp(-0.5 * np.linspace(-3, 3, 15)**2)
        kernel /= kernel.sum()
        smoothed = convolve(counts, kernel, mode="same")
        ax.plot(centers, smoothed, color="#D99A5E", linewidth=2.0, label="KDE")

    ax.set_xlabel("Value")
    ax.set_ylabel("Density")
    ax.set_title("Distribution with Kernel Density Estimation")
    ax.legend(loc="upper right")
    ax.grid(linestyle="--", linewidth=0.6, alpha=0.35)

    fig.tight_layout(pad=1.2)
    return fig

def save_figure(fig):
    path = OUTPUT_DIR / f"{FIG_NAME}.png"
    fig.savefig(path, dpi=DPI, bbox_inches="tight")
    print(f"Saved: {path}")

def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    save_figure(fig)

if __name__ == "__main__":
    main()