"""
Publication-quality figure: figure_horizontal_bar.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

OUTPUT_DIR = Path("docs/figures")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_horizontal_bar"
DPI = 150

PAPER_PALETTE = {
    "blue_main": "#5B8DB8",
    "blue_dark": "#3E6F95",
    "blue_light": "#BFD8EA",
    "teal_main": "#6FA8A6",
    "teal_dark": "#4D8583",
    "green_light": "#CFE8D5",
    "green_main": "#9CCB9E",
    "yellow_light": "#F3E6B3",
    "orange_light": "#E8B77D",
    "orange_main": "#D99A5E",
}

def apply_paper_style(font_size=12):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": 1.2,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })

def load_data():
    features = [
        "Spectral Power", "Time Domain", "Connectivity",
        "Cross-Frequency", "Nonlinear", "Entropy",
    ]
    importance = np.array([0.32, 0.28, 0.18, 0.12, 0.06, 0.04])
    return features, importance

def validate_data(data):
    features, importance = data
    assert len(features) == len(importance)

def plot_figure(data):
    apply_paper_style()
    features, importance = data

    fig, ax = plt.subplots(figsize=(7, 4.5))

    sorted_idx = np.argsort(importance)
    colors = ["#5B8DB8", "#6FA8A6", "#9CCB9E", "#F3E6B3", "#E8B77D", "#D99A5E"]

    bars = ax.barh(
        np.array(features)[sorted_idx],
        importance[sorted_idx],
        color=[colors[i % len(colors)] for i in range(len(features))],
        edgecolor="white",
        linewidth=0.5,
    )

    for bar in bars:
        width = bar.get_width()
        ax.annotate(f"{width:.2f}",
                    xy=(width, bar.get_y() + bar.get_height() / 2),
                    xytext=(3, 0), textcoords="offset points",
                    ha="left", va="center", fontsize=9)

    ax.set_xlabel("Importance Score")
    ax.set_title("Feature Importance Ranking")
    ax.grid(axis="x", linestyle="--", linewidth=0.6, alpha=0.35)

    fig.tight_layout(pad=1.2)
    return fig

def save_figure(fig):
    path = OUTPUT_DIR / f"{FIG_NAME}.png"
    fig.savefig(path, dpi=DPI, bbox_inches="tight")
    print(f"Saved: {path}")

def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    save_figure(fig)

if __name__ == "__main__":
    main()