"""
Publication-quality multi-panel figure: figure_multi_panel.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec


# =========================
# Config
# =========================

OUTPUT_DIR = Path("docs/figures")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_multi_panel"
SAVE_FORMATS = ["png"]
DPI = 150


# =========================
# Style
# =========================

PAPER_PALETTE = {

    "blue_main": "#5B8DB8",

    "blue_dark": "#3E6F95",

    "blue_light": "#BFD8EA",

    "teal_main": "#6FA8A6",

    "teal_dark": "#4D8583",

    "green_light": "#CFE8D5",

    "green_main": "#9CCB9E",

    "yellow_light": "#F3E6B3",

    "orange_light": "#E8B77D",

    "orange_main": "#D99A5E",

    "purple_light": "#C9BEDF",

    "pink_light": "#E7C1C0",

    "gray_light": "#E8ECEF",

    "gray": "#BFC7CD",

    "gray_dark": "#66727C",

    "positive": "#6FA8A6",

    "negative": "#D99A5E",

    "neutral": "#BFC7CD",

    "highlight": "#F3C567",

}


def apply_paper_style(font_size=12, linewidth=1.2):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": linewidth,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "svg.fonttype": "none",
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })


# =========================
# Data
# =========================

def load_data():

        # TODO: Replace this example data with your real data.
        panel_names = ["Accuracy", "Loss", "F1-Score", "Precision"]
        np.random.seed(42)
        data = {
            "Accuracy": np.array([0.72, 0.75, 0.78, 0.80, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87]),
            "Loss": np.array([0.45, 0.38, 0.32, 0.28, 0.24, 0.21, 0.19, 0.17, 0.16, 0.15]),
            "F1-Score": np.array([0.70, 0.73, 0.76, 0.78, 0.80, 0.82, 0.83, 0.84, 0.85, 0.86]),
            "Precision": np.array([0.68, 0.71, 0.74, 0.76, 0.78, 0.80, 0.81, 0.82, 0.83, 0.84]),
        }
        return panel_names, data


def validate_data(data):

        panel_names, data = data
        if len(data) != len(panel_names):
            raise ValueError(f"Expected {len(panel_names)} panels, got {len(data)}")
        for name in panel_names:
            if name not in data:
                raise ValueError(f"Panel {name} not found in data")


# =========================
# Plot
# =========================

def plot_figure(data):

        apply_paper_style()
        panel_names, data = data

        fig = plt.figure(figsize=(10, 7))
        gs = GridSpec(2, 2, figure=fig, hspace=0.35, wspace=0.30)

        colors = [
            "#5B8DB8",
            "#6FA8A6",
            "#9CCB9E",
        ]

        axes = []
        panel_labels = ["A", "B", "C", "D"]

        for i, (panel_name, label) in enumerate(zip(panel_names, panel_labels)):
            ax = fig.add_subplot(gs[i])
            axes.append(ax)

            values = data[panel_name]
            x = np.arange(len(values))

            if panel_name == "Loss":
                color = PAPER_PALETTE["orange_main"]
            else:
                color = colors[i % len(colors)]

            ax.plot(x, values, marker="o", color=color, linewidth=2.0, markersize=6)
            ax.set_xlabel("Iteration")
            ax.set_ylabel(panel_name)
            ax.set_title(f"{panel_name} Over Time")
            ax.grid(linestyle="--", linewidth=0.6, alpha=0.35)

            ax.text(-0.12, 1.02, label, transform=ax.transAxes,
                    fontsize=14, fontweight="bold", va="bottom", ha="right")

        return fig


# =========================
# Export
# =========================

def save_figure(fig, name=FIG_NAME):
    saved_paths = []
    for fmt in SAVE_FORMATS:
        path = OUTPUT_DIR / f"{name}.{fmt}"
        fig.savefig(path, dpi=DPI, bbox_inches="tight")
        saved_paths.append(path)
    return saved_paths


def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    saved_paths = save_figure(fig)
    print("Saved files:")
    for path in saved_paths:
        print(f"  - {path}")


if __name__ == "__main__":
    main()
