"""
Publication-quality figure: figure_permutation_test.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

OUTPUT_DIR = Path("docs/figures")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_permutation_test"
DPI = 150

def apply_paper_style(font_size=12):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": 1.2,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })

def load_data():
    np.random.seed(42)
    group_a = np.random.normal(0.72, 0.08, 30)
    group_b = np.random.normal(0.78, 0.07, 30)
    observed_diff = group_b.mean() - group_a.mean()
    n_permutations = 5000
    combined = np.concatenate([group_a, group_b])
    null_dist = np.zeros(n_permutations)
    for i in range(n_permutations):
        perm = np.random.permutation(combined)
        null_dist[i] = perm[:30].mean() - perm[30:].mean()
    p_value = (np.abs(null_dist) >= np.abs(observed_diff)).mean()
    return observed_diff, null_dist, p_value

def validate_data(data):
    observed_diff, null_dist, p_value = data
    assert len(null_dist) > 0

def plot_figure(data):
    apply_paper_style()
    observed_diff, null_dist, p_value = data

    fig, ax = plt.subplots(figsize=(7, 4.5))

    ax.hist(null_dist, bins=50, density=True, color="#5B8DB8", alpha=0.6,
            edgecolor="white", linewidth=0.5, label="Null Distribution")

    ax.axvline(observed_diff, color="#D99A5E", linewidth=2.0, linestyle="--",
               label=f"Observed ({observed_diff:.3f})")
    ax.axvline(-observed_diff, color="#D99A5E", linewidth=2.0, linestyle="--")

    extreme = null_dist[np.abs(null_dist) >= np.abs(observed_diff)]
    if len(extreme) > 0:
        ax.hist(extreme, bins=50, density=True, color="#D99A5E", alpha=0.4,
                edgecolor="white", linewidth=0.5)

    ax.annotate(f"p = {p_value:.4f}", xy=(0.95, 0.92), xycoords="axes fraction",
               ha="right", fontsize=10, fontweight="bold",
               bbox=dict(boxstyle="round,pad=0.3", facecolor="#F3E6B3", alpha=0.8))

    ax.set_xlabel("Difference in Means")
    ax.set_ylabel("Density")
    ax.set_title("Permutation Test: Distribution of Test Statistic Under H0")
    ax.legend(loc="upper left")
    ax.grid(linestyle="--", linewidth=0.6, alpha=0.35)

    fig.tight_layout(pad=1.2)
    return fig

def save_figure(fig):
    path = OUTPUT_DIR / f"{FIG_NAME}.png"
    fig.savefig(path, dpi=DPI, bbox_inches="tight")
    print(f"Saved: {path}")

def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    save_figure(fig)

if __name__ == "__main__":
    main()