"""
Publication-quality figure: figure_raincloud.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

try:
    from scipy.stats import gaussian_kde
except ImportError:
    gaussian_kde = None

OUTPUT_DIR = Path("docs/figures")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_raincloud"
DPI = 150

def apply_paper_style(font_size=12):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": 1.2,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })

def load_data():
    np.random.seed(42)
    groups = ["Control", "Treatment A", "Treatment B"]
    data = {
        "Control": np.random.normal(0.60, 0.10, 50),
        "Treatment A": np.random.normal(0.72, 0.09, 50),
        "Treatment B": np.random.normal(0.78, 0.08, 50),
    }
    return groups, data

def validate_data(data):
    groups, data = data
    assert len(data) == len(groups)

def plot_figure(data):
    apply_paper_style()
    groups, data = data

    fig, ax = plt.subplots(figsize=(8, 5))

    colors = ["#5B8DB8", "#6FA8A6", "#9CCB9E"]

    for i, (name, vals) in enumerate(zip(groups, [data[g] for g in groups])):
        pos = i
        color = colors[i % len(colors)]

        # KDE cloud (half violin)
        x_grid = np.linspace(vals.min() - 0.05, vals.max() + 0.05, 200)
        if gaussian_kde is not None:
            density = gaussian_kde(vals)(x_grid)
        else:
            bins_edges = np.histogram_bin_edges(vals, bins=20)
            counts, _ = np.histogram(vals, bins=bins_edges, density=True)
            centers = 0.5 * (bins_edges[:-1] + bins_edges[1:])
            kernel = np.exp(-0.5 * np.linspace(-3, 3, 15)**2)
            kernel /= kernel.sum()
            smoothed = np.convolve(counts, kernel, mode="same")
            density = np.interp(x_grid, centers, smoothed)
        density_scaled = density / density.max() * 0.4
        ax.fill_betweenx(x_grid, pos, pos + density_scaled, color=color, alpha=0.5)
        ax.plot(pos + density_scaled, x_grid, color=color, linewidth=1.2)

        # Boxplot
        bp = ax.boxplot(
            [vals], positions=[pos + 0.55], widths=0.15, vert=False,
            patch_artist=True,
            boxprops=dict(facecolor="white", edgecolor="gray", linewidth=1.0),
            whiskerprops=dict(color="gray", linewidth=1.0),
            capprops=dict(color="gray", linewidth=1.0),
            medianprops=dict(color="black", linewidth=1.5),
            showfliers=False,
        )

        # Rain (scattered points)
        y_jitter = np.random.uniform(pos + 0.75, pos + 0.95, size=len(vals))
        ax.scatter(y_jitter, vals, color=color, alpha=0.4, s=15,
                  edgecolors="white", linewidth=0.3)

    ax.set_yticks(range(len(groups)))
    ax.set_yticklabels(groups)
    ax.set_xlabel("Score")
    ax.set_title("Raincloud Plot: Distribution Comparison")
    ax.grid(axis="x", linestyle="--", linewidth=0.6, alpha=0.35)

    fig.tight_layout(pad=1.2)
    return fig

def save_figure(fig):
    path = OUTPUT_DIR / f"{FIG_NAME}.png"
    fig.savefig(path, dpi=DPI, bbox_inches="tight")
    print(f"Saved: {path}")

def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    save_figure(fig)

if __name__ == "__main__":
    main()