"""
Publication-quality figure: figure_scatter_regression.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

OUTPUT_DIR = Path("docs/figures")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_scatter_regression"
DPI = 150

def apply_paper_style(font_size=12):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": 1.2,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })

def load_data():
    np.random.seed(42)
    n = 60
    x = np.random.uniform(20, 80, n)
    y = 0.5 * x + 10 + np.random.normal(0, 8, n)
    return x, y

def validate_data(data):
    x, y = data
    assert len(x) == len(y)

def plot_figure(data):
    apply_paper_style()
    x, y = data

    fig, ax = plt.subplots(figsize=(6, 5))

    ax.scatter(x, y, color="#5B8DB8", alpha=0.6, s=40, edgecolors="white", linewidth=0.5)

    coeffs = np.polyfit(x, y, 1)
    x_line = np.linspace(x.min(), x.max(), 100)
    y_line = np.polyval(coeffs, x_line)
    ax.plot(x_line, y_line, color="#D99A5E", linewidth=2.0, label=f"y = {coeffs[0]:.2f}x + {coeffs[1]:.1f}")

    corr = np.corrcoef(x, y)[0, 1]
    ax.annotate(f"r = {corr:.3f}", xy=(0.05, 0.92), xycoords="axes fraction", fontsize=10)

    ax.set_xlabel("Feature Value")
    ax.set_ylabel("Response")
    ax.set_title("Scatter Plot with Regression Line")
    ax.legend(loc="lower right")
    ax.grid(linestyle="--", linewidth=0.6, alpha=0.35)

    fig.tight_layout(pad=1.2)
    return fig

def save_figure(fig):
    path = OUTPUT_DIR / f"{FIG_NAME}.png"
    fig.savefig(path, dpi=DPI, bbox_inches="tight")
    print(f"Saved: {path}")

def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    save_figure(fig)

if __name__ == "__main__":
    main()