"""
Publication-quality figure: figure_stacked_bar.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

OUTPUT_DIR = Path("docs/figures")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_stacked_bar"
DPI = 150

PAPER_PALETTE = {
    "blue_main": "#5B8DB8",
    "blue_dark": "#3E6F95",
    "blue_light": "#BFD8EA",
    "teal_main": "#6FA8A6",
    "teal_dark": "#4D8583",
    "green_light": "#CFE8D5",
    "green_main": "#9CCB9E",
    "yellow_light": "#F3E6B3",
    "orange_light": "#E8B77D",
    "orange_main": "#D99A5E",
}

def apply_paper_style(font_size=12):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": 1.2,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })

def load_data():
    categories = ["Model A", "Model B", "Model C", "Model D"]
    components = ["Conv", "Attention", "FC", "Other"]
    data = np.array([
        [0.40, 0.25, 0.20, 0.15],
        [0.20, 0.45, 0.20, 0.15],
        [0.25, 0.30, 0.35, 0.10],
        [0.15, 0.35, 0.25, 0.25],
    ])
    return categories, components, data

def validate_data(data):
    categories, components, data = data
    assert data.shape == (len(categories), len(components))
    for row in data:
        assert abs(row.sum() - 1.0) < 0.01, f"Row sums to {row.sum()}, expected ~1.0"

def plot_figure(data):
    apply_paper_style()
    categories, components, data = data

    fig, ax = plt.subplots(figsize=(7, 5))

    colors = ["#5B8DB8", "#6FA8A6", "#9CCB9E", "#F3E6B3"]
    x = np.arange(len(categories))
    bottom = np.zeros(len(categories))

    for i, comp in enumerate(components):
        ax.bar(x, data[:, i], bottom=bottom, label=comp,
               color=colors[i % len(colors)], edgecolor="white", linewidth=0.5)
        bottom += data[:, i]

    ax.set_xticks(x)
    ax.set_xticklabels(categories)
    ax.set_ylabel("Proportion")
    ax.set_title("Model Component Breakdown")
    ax.legend(loc="upper right", ncol=2)
    ax.set_ylim(0, 1.05)
    ax.grid(axis="y", linestyle="--", linewidth=0.6, alpha=0.35)

    fig.tight_layout(pad=1.2)
    return fig

def save_figure(fig):
    path = OUTPUT_DIR / f"{FIG_NAME}.png"
    fig.savefig(path, dpi=DPI, bbox_inches="tight")
    print(f"Saved: {path}")

def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    save_figure(fig)

if __name__ == "__main__":
    main()