"""
Publication-quality figure: figure_ternary.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.tri as tri

OUTPUT_DIR = Path("docs/figures")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_ternary"
DPI = 150

def apply_paper_style(font_size=12):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": 1.2,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })

def load_data():
    np.random.seed(42)
    n = 30
    a = np.random.dirichlet([2, 3, 1], n)
    classes = np.random.choice(["Type I", "Type II", "Type III"], n)
    return a, classes

def validate_data(data):
    a, classes = data
    assert a.shape[0] == len(classes)

def plot_figure(data):
    apply_paper_style()
    a, classes = data

    fig, ax = plt.subplots(figsize=(6, 5.5))

    # Convert to 2D barycentric coordinates
    x = 0.5 * (2 * a[:, 1] + a[:, 2]) / (a[:, 0] + a[:, 1] + a[:, 2])
    y = (np.sqrt(3) / 2) * a[:, 2] / (a[:, 0] + a[:, 1] + a[:, 2])

    color_map = {"Type I": "#5B8DB8", "Type II": "#6FA8A6", "Type III": "#D99A5E"}
    for cls in ["Type I", "Type II", "Type III"]:
        mask = classes == cls
        ax.scatter(x[mask], y[mask], c=color_map[cls], label=cls, s=50,
                  alpha=0.7, edgecolors="white", linewidth=0.5)

    # Draw triangle border
    triangle_x = [0, 0.5, 1.0, 0]
    triangle_y = [0, np.sqrt(3)/2, 0, 0]
    ax.plot(triangle_x, triangle_y, "k-", linewidth=1.0)

    # Labels at vertices
    ax.text(-0.05, -0.03, "Component A", ha="center", fontsize=9)
    ax.text(0.5, np.sqrt(3)/2 + 0.03, "Component C", ha="center", fontsize=9)
    ax.text(1.05, -0.03, "Component B", ha="center", fontsize=9)

    ax.set_xlim(-0.1, 1.1)
    ax.set_ylim(-0.1, np.sqrt(3)/2 + 0.1)
    ax.set_aspect("equal")
    ax.axis("off")
    ax.set_title("Ternary Composition Diagram")
    ax.legend(loc="upper right")

    fig.tight_layout(pad=1.2)
    return fig

def save_figure(fig):
    path = OUTPUT_DIR / f"{FIG_NAME}.png"
    fig.savefig(path, dpi=DPI, bbox_inches="tight")
    print(f"Saved: {path}")

def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    save_figure(fig)

if __name__ == "__main__":
    main()