"""
Publication-quality figure: figure_line_with_ci.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# =========================
# Config
# =========================

OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_line_with_ci"
SAVE_FORMATS = ["png", "pdf", "svg"]
DPI = 300


# =========================
# Style
# =========================

PAPER_PALETTE = {

    "blue_main": "#5B8DB8",

    "blue_dark": "#3E6F95",

    "blue_light": "#BFD8EA",

    "teal_main": "#6FA8A6",

    "teal_dark": "#4D8583",

    "green_light": "#CFE8D5",

    "green_main": "#9CCB9E",

    "yellow_light": "#F3E6B3",

    "orange_light": "#E8B77D",

    "orange_main": "#D99A5E",

    "purple_light": "#C9BEDF",

    "pink_light": "#E7C1C0",

    "gray_light": "#E8ECEF",

    "gray": "#BFC7CD",

    "gray_dark": "#66727C",

    "positive": "#6FA8A6",

    "negative": "#D99A5E",

    "neutral": "#BFC7CD",

    "highlight": "#F3C567",

}


def apply_paper_style(font_size=12, linewidth=1.2):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": linewidth,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "svg.fonttype": "none",
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })


# =========================
# Data
# =========================

def load_data():

        # TODO: Replace this example data with your real data.
        series_names = ["Train", "Validation"]
        epochs = list(range(1, 21))
        data = {
            "Train": [0.5725, 0.6319, 0.6805, 0.7203, 0.7528, 0.7795, 0.8014, 0.8192, 0.8339, 0.8459, 0.8557, 0.8637, 0.8703, 0.8757, 0.8801, 0.8837, 0.8867, 0.8891, 0.8911, 0.8927],
            "Validation": [0.5536, 0.5968, 0.6327, 0.6636, 0.6914, 0.7173, 0.7420, 0.7656, 0.7879, 0.8083, 0.8263, 0.8410, 0.8519, 0.8587, 0.8613, 0.8601, 0.8557, 0.8488, 0.8407, 0.8324],
        }
        confidence_intervals = {
            "Train": (np.array([0.65] * 20), np.array([0.75] * 20)),
            "Validation": (np.array([0.72] * 20), np.array([0.82] * 20)),
        }
        return series_names, epochs, data, confidence_intervals


def validate_data(data):

        series_names, epochs, data, confidence_intervals = data
        if len(data) != len(series_names):
            raise ValueError(f"Expected {len(series_names)} series, got {len(data)}")
        for name in series_names:
            if name not in data:
                raise ValueError(f"Series {name} not found in data")
            if len(data[name]) != len(epochs):
                raise ValueError(f"Series {name}: expected {len(epochs)} values, got {len(data[name])}")


# =========================
# Plot
# =========================

def plot_figure(data):

        apply_paper_style()
        series_names, epochs, data, confidence_intervals = data

        fig, ax = plt.subplots(figsize=(7, 4.5))

        colors = [
            "#5B8DB8",
            "#6FA8A6",
        ]

        for i, name in enumerate(series_names):
            color = colors[i % len(colors)]
            values = data[name]
            ax.plot(epochs, values, label=name, color=color, linewidth=2.0)
            if name in confidence_intervals:
                lower, upper = confidence_intervals[name]
                ax.fill_between(epochs, lower, upper, color=color, alpha=0.2)

        ax.set_xlabel("Training Epoch")
        ax.set_ylabel("Accuracy")
        ax.set_title("Training Curve with 95% Confidence Interval")
        ax.legend(loc="lower right")
        ax.grid(linestyle="--", linewidth=0.6, alpha=0.35)
        ax.set_ylim(0.5, 1.0)

        fig.tight_layout(pad=1.2)
        return fig


# =========================
# Export
# =========================

def save_figure(fig, name=FIG_NAME):
    saved_paths = []
    for fmt in SAVE_FORMATS:
        path = OUTPUT_DIR / f"{name}.{fmt}"
        fig.savefig(path, dpi=DPI, bbox_inches="tight")
        saved_paths.append(path)
    return saved_paths


def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    saved_paths = save_figure(fig)
    print("Saved files:")
    for path in saved_paths:
        print(f"  - {path}")


if __name__ == "__main__":
    main()
