"""
Publication-quality figure: figure_violin_box_scatter.

Generated by paper-figure-codegen.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# =========================
# Config
# =========================

OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FIG_NAME = "figure_violin_box_scatter"
SAVE_FORMATS = ["png", "pdf", "svg"]
DPI = 300


# =========================
# Style
# =========================

PAPER_PALETTE = {

    "blue_main": "#5B8DB8",

    "blue_dark": "#3E6F95",

    "blue_light": "#BFD8EA",

    "teal_main": "#6FA8A6",

    "teal_dark": "#4D8583",

    "green_light": "#CFE8D5",

    "green_main": "#9CCB9E",

    "yellow_light": "#F3E6B3",

    "orange_light": "#E8B77D",

    "orange_main": "#D99A5E",

    "purple_light": "#C9BEDF",

    "pink_light": "#E7C1C0",

    "gray_light": "#E8ECEF",

    "gray": "#BFC7CD",

    "gray_dark": "#66727C",

    "positive": "#6FA8A6",

    "negative": "#D99A5E",

    "neutral": "#BFC7CD",

    "highlight": "#F3C567",

}


def apply_paper_style(font_size=12, linewidth=1.2):
    plt.rcParams.update({
        "font.family": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": font_size,
        "axes.linewidth": linewidth,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "svg.fonttype": "none",
        "figure.dpi": DPI,
        "savefig.dpi": DPI,
        "savefig.bbox": "tight",
    })


# =========================
# Data
# =========================

def load_data():

        # TODO: Replace this example data with your real data.
        group_names = ["Model A", "Model B", "Model C"]
        data = {
            "Model A": np.array([0.7897, 0.7389, 0.8018, 0.8718, 0.7313, 0.7313, 0.8763, 0.8114, 0.7124, 0.7934, 0.7129, 0.7127, 0.7694, 0.5969, 0.6120, 0.7050, 0.6690, 0.7751, 0.6774, 0.6370, 0.8673, 0.7319, 0.7554, 0.6360, 0.7064, 0.7589, 0.6579, 0.7801, 0.7019, 0.7267, 0.7019, 0.8982, 0.7489, 0.6654, 0.8158, 0.6523, 0.7667, 0.5932, 0.6437, 0.7657, 0.8091, 0.7637, 0.7407, 0.7259, 0.6317, 0.6924, 0.7131, 0.8346, 0.7775, 0.6090]),
            "Model B": np.array([0.8394, 0.7969, 0.7794, 0.8567, 0.8819, 0.8759, 0.7696, 0.8014, 0.8399, 0.8785, 0.7912, 0.8089, 0.7536, 0.7482, 0.8688, 0.9014, 0.8157, 0.8802, 0.8417, 0.7813, 0.8417, 0.9123, 0.8179, 0.9139, 0.6628, 0.8693, 0.8252, 0.8021, 0.8255, 0.7007, 0.8068, 0.8414, 0.9087, 0.7889, 0.7715, 0.7899, 0.8749, 0.8397, 0.7882, 0.8508, 0.8258, 0.8781, 0.7779, 0.8003, 0.7965, 0.7322, 0.8378, 0.8357, 0.8203, 0.8059]),
            "Model C": np.array([0.8092, 0.8590, 0.8629, 0.8399, 0.8719, 0.9002, 0.9743, 0.8887, 0.8929, 0.8763, 0.7841, 0.8787, 0.8830, 1.0032, 0.8704, 0.8951, 0.8783, 0.8216, 0.9371, 0.9176, 0.9196, 0.8345, 0.9501, 0.8099, 0.9093, 0.9895, 0.8305, 0.8517, 0.8850, 0.8548, 0.8025, 0.8834, 0.8269, 0.9037, 0.8340, 0.9575, 0.8408, 0.8639, 0.9207, 0.8185, 0.8914, 0.9454, 0.7996, 0.8892, 0.8930, 0.9191, 0.8182, 0.8140, 0.9061, 0.8948]),
        }
        return group_names, data


def validate_data(data):

        group_names, data = data
        if len(data) != len(group_names):
            raise ValueError(f"Expected {len(group_names)} groups, got {len(data)}")
        for name in group_names:
            if name not in data:
                raise ValueError(f"Group {name} not found in data")
            if len(data[name]) < 5:
                print(f"Warning: Group {name} has only {len(data[name])} samples")


# =========================
# Plot
# =========================

def plot_figure(data):

        apply_paper_style()
        group_names, data = data

        fig, ax = plt.subplots(figsize=(7, 5))

        colors = [
            "#5B8DB8",
            "#6FA8A6",
            "#9CCB9E",
        ]

        positions = np.arange(1, len(group_names) + 1)

        violin_parts = ax.violinplot(
            [data[name] for name in group_names],
            positions=positions,
            showmeans=False,
            showmedians=False,
            showextrema=False,
        )
        for i, pc in enumerate(violin_parts["bodies"]):
            pc.set_facecolor(colors[i % len(colors)])
            pc.set_alpha(0.6)

        box_plots = ax.boxplot(
            [data[name] for name in group_names],
            positions=positions,
            widths=0.3,
            patch_artist=True,
            showfliers=False,
            boxprops=dict(facecolor="white", edgecolor="gray", linewidth=1.2),
            whiskerprops=dict(color="gray", linewidth=1.2),
            capprops=dict(color="gray", linewidth=1.2),
            medianprops=dict(color="black", linewidth=1.5),
        )

        for i, (pos, name) in enumerate(zip(positions, group_names)):
            group_data = data[name]
            x_jitter = np.random.normal(pos, 0.04, size=len(group_data))
            ax.scatter(x_jitter, group_data, color=colors[i % len(colors)],
                      alpha=0.5, s=20, edgecolors="white", linewidth=0.5)

        ax.set_xticks(positions)
        ax.set_xticklabels(group_names)
        ax.set_ylabel("Accuracy")
        ax.set_title("Distribution Comparison: Violin + Box + Scatter")
        ax.grid(axis="y", linestyle="--", linewidth=0.6, alpha=0.35)
        ax.set_ylim(0.4, 1.0)

        fig.tight_layout(pad=1.2)
        return fig


# =========================
# Export
# =========================

def save_figure(fig, name=FIG_NAME):
    saved_paths = []
    for fmt in SAVE_FORMATS:
        path = OUTPUT_DIR / f"{name}.{fmt}"
        fig.savefig(path, dpi=DPI, bbox_inches="tight")
        saved_paths.append(path)
    return saved_paths


def main():
    data = load_data()
    validate_data(data)
    fig = plot_figure(data)
    saved_paths = save_figure(fig)
    print("Saved files:")
    for path in saved_paths:
        print(f"  - {path}")


if __name__ == "__main__":
    main()
